name: mobile
description: "Aplicación móvil HACO"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2                # Para manejar estado
  http: ^1.2.2                    # Para consumir API
  flutter_native_splash: ^2.3.9   # Splash screen
  shared_preferences: ^2.3.2      # Almacenamiento local
  flutter_secure_storage: ^9.0.0  # Almacenamiento seguro

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#F1F1F1"   # Fondo gris
  image: assets/images/unilogo.png
  android: true
  ios: true
  web: false

  android_12:
    image: assets/images/unilogo.png
    icon_background_color: "#F1F1F1"