version: '3.9'
name: saori-credibueno

services:
  db:
    image: mariadb:10.6.20
    container_name: saori_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - saori_network
    ports:
      - "3308:3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saori_php
    environment:
      - DOCKER=true
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/www/logs
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - saori_network
    ports:
      - "8082:80"
    depends_on:
      - db
    command: bash -c "chown -R www-data:www-data /var/www/html && find /var/www/html -type d -exec chmod 755 {} \\; && find /var/www/html -type f -exec chmod 644 {} \\; && apache2-foreground"

volumes:
  db_data:

networks:
  saori_network: